species:
  - Austrolebias_charrua
  - Nematolebias_whitei
  - Cynopoecilus_melanotaenia
  - Austrofundulus_limnaeus
  - Kryptolebias_marmoratus
  - Nothobranchius_furzeri
  - Oryzias_latipes

NCPU: 5
